### ISSUE TITLE
windows preferences

### ISSUE THREAD

**Issue by b4zz4** [inkscape/inkscape#11]
#I wanna that the floating windows are windows of type "*dialog" or "utility".  To be able to modify the style of window, without that confuse  with the main window

---

[es]
yo desearia que las ventanas flotantes de preferencias figuren en el sistema como ventanas de utilidades o dialogo, de modo de poder presonalizarlas.
[/es]

**Comment by fulldecent** [comment]
Reported upstream https://bugs.launchpad.net/inkscape/+bug/1568624
