### ISSUE TITLE
Snap control access from menu bar

### ISSUE THREAD

**Issue by budislav** [inkscape/inkscape#12]
User need to have access to all snap controls from menu bar>View, because he can hide "Snap control bar" which is awesome option.

![snap](https://cloud.githubusercontent.com/assets/3619927/14338044/c2c73390-fc73-11e5-9929-60aa5e42ed26.png)

**Comment by fulldecent** [comment]
Report upstream to https://bugs.launchpad.net/inkscape/+bug/1568623
