### ISSUE TITLE
User-friendly dockable dialog workflow

### ISSUE THREAD

**Issue by budislav** [inkscape/inkscape#13]
Inkscape have confusing system for accessing to dockable dialogs. Don't know is this bug but if not this is very confusing. From image below you can see six dialogs in one group and I can open and see only one dialog in one time. I want to have open all dialogs but it is impossible.

![dialogs](https://cloud.githubusercontent.com/assets/3619927/14338369/de35c2f6-fc76-11e5-8cb9-531cb58aa211.png)

Dialogs should be placed one below the other and possibility to open all of them if he need. Also collapsible like this menu http://www.jqueryscript.net/demo/jQuery-Vertical-Collapsible-Menu-with-Multiple-Transition-Effects/

Iconify dock option absolutely makes thing more confusing. Also reading vertical text is impossible without rotating your head.

![iconify](https://cloud.githubusercontent.com/assets/3619927/14338826/37165c20-fc7a-11e5-82c3-2b71a389981e.png)

Also user see same dialog title on two places

![same](https://cloud.githubusercontent.com/assets/3619927/14338880/b948069e-fc7a-11e5-93b7-46fe38129dd1.png)

That's all very confusing. The best solution will be to have collapsible dialogs one below the other(never in group).

![solution](https://cloud.githubusercontent.com/assets/3619927/14339588/0ec1937e-fc80-11e5-9983-2460febbef92.png)

All dockable dialogs should be accessible from one place from menu bar>View>Dialogs. From there you can show or hide dialog you want. Also one more way for removing dialog is right click on dialog title and click on "remove" to remove dialog.

**Comment by fulldecent** [comment]
Reported upstream to https://bugs.launchpad.net/inkscape/+bug/1568622
