### ISSUE TITLE
Wrong dash-array interpretation.

### ISSUE THREAD

**Issue by Evil-Spirit** [inkscape/inkscape#14]
When we want to make dash-dot pattern like this
```
stroke-dasharray:2.500,1.250,0,1.250;
stroke-dasharray:2.500,1.250,0,1.250,0,1.250;
```
the dots has lost.
but if we create the pure dot pattern:
`stroke-dasharray:0,5.000;`
all is fine.

The sample:
https://github.com/whitequark/solvespace-testcases/blob/master/tests/stippled/stippled.svg

**Comment by fulldecent** [comment]
Reported upstream to https://bugs.launchpad.net/inkscape/+bug/1568620
