### ISSUE TITLE
full history of inkscape on github

### ISSUE THREAD

**Issue by johnyf** [inkscape/inkscape#18]
Currently, the history has been squashed and is not very usable. Are there any plans to mirror the actual history from `bzr`? Even better, are there any plans to use `git` and stop using `bzr`?

**Comment by christofferholmstedt** [comment]
There are plans to move to Git, exactly when is not decided yet but the 2geom lib has already made the move.

**Comment by fulldecent** [comment]
I am working to get all revisions in, including original commit messages, authorship, and timestamps. This is currently going into branch `bzr-original`.

The only exception between `bzr-original` and the actual bzr is a new `.gitignore`.

**Comment by fulldecent** [comment]
Document to put in the `master` branch some time:

```bash
# INITIALIZE

cp -r inkscape/ inkscape-bzr-original
cd inkscape-bzr-original/
git checkout --orphan bzr-original
git rm -rf .
vim .gitignore
git add .gitignore 
git commit --date=2000-01-01 --message='Initial commit with .gitignore'
git push

# MIGRATE FIRST REVISION

REVNO=1
bzr revert -r$REVNO
bzr log -r$REV --long > /tmp/bzrimporttmp
COMMITTER=$(cat /tmp/bzrimporttmp | sed -ne 's/^committer: //p')
TIMESTAMP=$(cat /tmp/bzrimporttmp | sed -ne 's/^timestamp: //p')
MESSAGE=$(cat /tmp/bzrimporttmp | sed -ne '/^message:/{s///; :a' -e 'n;p;ba' -e '}')
git add .
git commit --all --author="$COMMITTER" --date="$TIMESTAMP" --message="$REVNO: $MESSAGE"

# AUTOMATE THE REST...

git checkout bzr-original
git pull origin bzr-original
REVNO=$(git log -1 --oneline | sed -ne 's/^[^ ]* *\([1-9]\).*/\1/p')
LATEST_AVAILABLE=$(bzr version-info | sed -ne 's/^revno: //p')
while [ $REVNO -lt $LATEST_AVAILABLE ]; do
  let REVNO=REVNO+1
  echo "DOING $REVNO"
  bzr revert -r$REVNO
  bzr log -r$REVNO --long > /tmp/bzrimporttmp
  COMMITTER=$(cat /tmp/bzrimporttmp | sed -ne 's/^committer: //p')
  TIMESTAMP=$(cat /tmp/bzrimporttmp | sed -ne 's/^timestamp: //p')
  MESSAGE=$(cat /tmp/bzrimporttmp | sed -ne '/^message:/{s///; :a' -e 'n;p;ba' -e '}')
  git add .
  git commit --all --author="$COMMITTER" --date="$TIMESTAMP" --message="$REVNO: $MESSAGE"
  git push origin bzr-original
done
```

**Comment by fulldecent** [comment]
@johnyf Please take a look at the new branch and let me know if it is coming through correctly. This is my first migration, not sure if I'm doing it right!

**Comment by johnyf** [comment]
You might want to try also [`bzr fast-export`](http://doc.bazaar.canonical.com/plugins/en/fastimport-plugin.html) and [`git fast-import`](https://git-scm.com/docs/git-fast-import), which are widely used. I have successfully used fast-export to convert from `hg` to `git` repos in the past.
An [example](https://git-scm.com/docs/git-fast-import) in a blog.

It would also be useful to tag the commits that correspond to past releases, with `git tag -a -m ...`. I expect that `fast-export` should include exporting release tags.

The latest commit 907a819b7f3192079a1dec47e6ce22b49c38f94b on branch `bzr-original` is dated Aug 4, 2007, so I assume there are more commits to be imported. A [`.gitattributes` file](https://github.com/tulip-control/tulip-control/blob/dfdbb717cb18c363efb9e3da2ad1cd7ed9bee1cf/.gitattributes) would be good to add, in order to ensure consistent newlines.

Also, the `master` branch will need to be replaced, and this needs to happen in a way that will not cause confusion. It is close to rolling back public history, though in this case it is a replacement of the repository.

It is probably also worth migrating the bug tracker to github.

**Comment by fulldecent** [comment]
Yes, the history is still being added in. This is very slow but should be done in the next few days.

I have tried using `fast-export` but I had problems with Python modules that I could not figure out.

So far my plan for MINIMAL VIABLE PRODUCT is:

 - [ ] Finish syncing history into `bzr-original`
 - [ ] Update `master` with notes about what is going on and remove source code from `master`
 - [ ] Learn about `.gitignore` and consider implementing it (may require transcribing `bzr-original` to `bzr-original2` and replaying each commit)
 - [ ] Synchronize tags (help needed)
 - [ ] Add the latest release

Then the team can decide if we want to start developing using github. If so, cutover is:

 - [ ] Update `bzr-original` or `bzr-original2` and add a GitHub-friendly README.md
 - [ ] Take the latest git commit from `bzr-original` or `bzr-original2` and commit to bzr (the only difference will be `README.md', `.gitignore` and maybe `.gitattributes`.
 - [ ] Make bzr readonly
 - [ ] Delete the `master` branch and rename `bzr-original` or `bzr-original2` to `master`

Now commits are being made to GitHub. If you fix a bug on bzr, still include the text "FIXES 9999" and then you manually have to mark that bug as fixed. The last step is:

 - [ ] Migrate all LaunchPad bugs to GitHub
 - [ ] For each migrated bug, search commit history, mark as closed with a commit reference if "fixes ###" is found

**Comment by christofferholmstedt** [comment]
Just out of curiosity, do you @johnyf and @fulldecent follow the Inkscape development mailing list?

Here is the discussion from earlier this year https://sourceforge.net/p/inkscape/mailman/inkscape-devel/thread/CAFLw2WT4fkq8RLEKaOkSf4Ug5kQc%2BdLpJRKJdfjwhP7hFmKp%3Dw%40mail.gmail.com/#msg34825547

**Comment by fulldecent** [comment]
Thanks for pointing this out. Right now I have been trying lots of ways to import issues, none of which are satisfactory.

Only the GitHub import-issues beta API will be sufficient for our task.

**Comment by fulldecent** [comment]
All synchronization documentation is moved to https://github.com/inkscape/inkscape/wiki/Synchronization-task

**Comment by fulldecent** [comment]
The full history is migrated, closing issue. Now tracking transition from Launchpad to GitHub is this issue #21.
