### ISSUE TITLE
exploding number of swatches (indirect linearGradients)

### ISSUE THREAD

**Issue by dynnamitt** [inkscape/inkscape#19]
0.91 Linux

[my-floor-4real-wrk001.svg.zip](https://github.com/inkscape/inkscape/files/325358/my-floor-4real-wrk001.svg.zip)

As soon as I move around a set of rect's that is using swatches (xml is generated outside inkscape) .. each one gets a linearGradient w xlink:href back to original swatch.. 
This makes it impossible for me to search for rects having refs back to my original swatch !

This didn't happen in a previous version

**Comment by dynnamitt** [comment]
mailed it upstream.. where can I follow progress?

**Comment by dynnamitt** [comment]
https://sourceforge.net/p/inkscape/mailman/inkscape-devel/?viewmonth=201606&viewday=21&style=threaded

**Comment by doctormo** [comment]
Thanks for filing this bug report about Inkscape.  This is not an actively monitored bug reporting location for the Inkscape project, however.  The official place to file bug reports is:

    https://bugs.launchpad.net/inkscape/+filebug

For more information on making good bug reports, please read:

    https://inkscape.org/en/contribute/report-bugs/

Thanks again,
Martin Owens
