### ISSUE TITLE
Migrate Launchpad to GitHub

### ISSUE THREAD

**Issue by fulldecent** [inkscape/inkscape#21]
Right now all Launchpad code is synced to `bzr-original` branch, actual development and issue reporting happen on Launchpad. This plan shows how to switch over to using GitHub for all development.

Work plan for MINIMAL VIABLE PRODUCT to start committing code to GitHub:

 - [x] Finish syncing history into `bzr-original`
 - [x] Update `master` with notes about what is going on and remove source code from `master`
 - [ ] Improve `.gitignore` and consider rewriting `bzr-original` history with it (replay each commit)
 - [x] Synchronize tags (help needed)
 - [ ] Add the latest release (and maybe others) binaries

Then the team can decide if we want to start developing using github. If so, cutover is:

 - [ ] Update `bzr-original` and add a GitHub-friendly README.md
 - [ ] Take the latest git commit here and commit to bzr (the only difference will be `README.md', `.gitignore` and maybe `.gitattributes` (for historical purposes)
 - [ ] Make Launchpad/bzr readonly
 - [ ] Delete the `master` branch here and rename `bzr-original` to `master`

Now commits are being made to GitHub. If you fix a bug from Launchpad, add like "FIXES 9999" to the commit text and manually mark that bug as fixed in Launchpad. This is a stable and doable development process. The following steps fully retire Launchpad and can happen whenever convenient:

 - [ ] Migrate all LaunchPad bugs to GitHub
 - [ ] For each migrated bug, search commit history, mark as closed with a commit reference if "fixes ###" is found
 - [ ] Add other past releases

**Comment by shakaran** [comment]
See #23 should help with the task "Update bzr-original and add a GitHub-friendly README.md"

**Comment by doctormo** [comment]
Thanks for filing this bug report about Inkscape.  This is not an actively monitored bug reporting location for the Inkscape project, however.  The official place to file bug reports is:

    https://bugs.launchpad.net/inkscape/+filebug

For more information on making good bug reports, please read:

    https://inkscape.org/en/contribute/report-bugs/

Thanks again,
Martin Owens
