### ISSUE TITLE
Could not register user in Inkscape's wiki

### ISSUE THREAD

**Issue by shakaran** [inkscape/inkscape#24]
I would like to [edit this page](http://wiki.inkscape.org/wiki/index.php/Compiling_Inkscape) for add the new instructions for github. See issue #23 but I cannot find any link in the wiki to register and edit the page as contribution

**Comment by doctormo** [comment]
Thanks for filing this bug report about Inkscape.  This is not an actively monitored bug reporting location for the Inkscape project, however.  The official place to file bug reports is:

    https://bugs.launchpad.net/inkscape/+filebug

For more information on making good bug reports, please read:

    https://inkscape.org/en/contribute/report-bugs/

Thanks again,
Martin Owens
