### ISSUE TITLE
Ubuntu 16.04 compile source missing packages

### ISSUE THREAD

**Issue by shakaran** [inkscape/inkscape#25]
In the [wiki page](http://wiki.inkscape.org/wiki/index.php/CompilingUbuntu) appears this command line:

    sudo apt-get install libgnome-vfsmm-2.6-dev libssl-dev libmagick++9-dev libwpg-dev libcdr-dev libvisio-dev

But the package libmagick++9-dev and the package libgnome-vfsmm-2.6-dev is not present in the repositories. it would be needed update the recommended packages for build from source in Ubuntu 16.04

**Comment by doctormo** [comment]
Thanks for filing this bug report about Inkscape.  This is not an actively monitored bug reporting location for the Inkscape project, however.  The official place to file bug reports is:

    https://bugs.launchpad.net/inkscape/+filebug

For more information on making good bug reports, please read:

    https://inkscape.org/en/contribute/report-bugs/

Thanks again,
Martin Owens
