### ISSUE TITLE
Emergency save activated!

### ISSUE THREAD

**Issue by YuGiOhJCJ** [inkscape/inkscape#27]
Hello,
I built inkscape-0.91 on Slackware64-14.2.
When I exit the application I see this message in the console: "Emergency save activated!".
Moreover, the application is not responding.
Any idea how to solve that please?
Thank you.
Best regards.

**Comment by shlomif** [comment]
I think you should report that problem on the launchpad issue tracker - not here on GitHub.

**Comment by YuGiOhJCJ** [comment]
I finally solved the problem.
I have restored my official operating system packages and removed the patch I have applied to the Inkscape code source.
So maybe it was a problem with my custom operating system packages (gtk+, gcc, ...) or my patch applied to the Inkscape source code.
I close the ticket.
