### ISSUE TITLE
Inkscape 0.48: Paste Style -> Opacity not pasted on increase

### ISSUE THREAD

**Issue by Modanung** [inkscape/inkscape#3]
Opacity setting for object is not pasted upon Paste Style when the pasted opacity is higher then the current one.

**Comment by luzfcb** [comment]
@Modanung this is a unofficial repository, please report the issue here: https://inkscape.org/en/contribute/report-bugs/

**Comment by fulldecent** [comment]
@Modanung Actually I can't get Paste Style to do anything.

Can you please include a video or animated gif showing this behavior. Also, let us know version and OS.

**Comment by Modanung** [comment]
This was in Inkscape 0.48 on Xubuntu 14.10.
I'll give it a try in Inkscape 0.91.

**Comment by Modanung** [comment]
...and it's already fixed. Awesome!
My apologies for wasting energy.

**Comment by Modanung** [comment]
@fulldecent In Inkscape 0.48:
Create two shapes, set the opacity (below blur) lower than 100% for one of them. Duplicate both of them and put them side by side. Copying the full opacity object and pasting it's style to the other will apply the entire style except for the increased opacity. The other way around it works just fine.

But apparently that was with year-old binaries.
