### ISSUE TITLE
bitmap font generator

### ISSUE THREAD

**Issue by L2L2L** [inkscape/inkscape#4]
Adding bitmap font generator to Inkscape.

Or is there an add-on already for this?

**Comment by RenaKunisaki** [comment]
What would it even do? Create bitmap fonts? That seems quite outside the scope of Inkscape, but an extension could probably do it.

**Comment by fulldecent** [comment]
Reported upstream to https://bugs.launchpad.net/inkscape-web/+bug/1535899

**Comment by fulldecent** [comment]
Moved to correct location https://bugs.launchpad.net/inkscape/+bug/1471386

**Comment by fulldecent** [comment]
Marking as enhancement. This is currently marked on the Inkscape wishlist.
