### ISSUE TITLE
EPS Support

### ISSUE THREAD

**Issue by jeroldhaas** [inkscape/inkscape#6]
I was very confused upon discovering I couldn't open a EPS file in Inkscape.

Inkscape 0.91

**Comment by fulldecent** [comment]
Thank you. This is already reported upstream

Duplicate https://bugs.launchpad.net/inkscape?field.searchtext=open+eps&search=Search&field.status%3Alist=NEW&field.status%3Alist=INCOMPLETE_WITH_RESPONSE&field.status%3Alist=INCOMPLETE_WITHOUT_RESPONSE&field.status%3Alist=CONFIRMED&field.status%3Alist=TRIAGED&field.status%3Alist=INPROGRESS&field.status%3Alist=FIXCOMMITTED&field.assignee=&field.bug_reporter=&field.omit_dupes=on&field.has_patch=&field.has_no_package=
