### ISSUE TITLE
Is it possible to open a new document in a new tab and not new window?

### ISSUE THREAD

**Issue by ismnoiet** [inkscape/inkscape#7]
Is it possible to open a new document in a new tab instead of a new window ?
Is there any options to achieve this ? 
Thank you in advance.

**Comment by fulldecent** [comment]
Posted upstream to https://answers.launchpad.net/inkscape/+question/281198

**Comment by fulldecent** [comment]
Closing, closed upstream at https://answers.launchpad.net/inkscape/+question/281198 this is wontfix right now.
